-- MySQL Script generated by MySQL Workbench
-- 05/21/18 18:27:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Proyecto_III
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Proyecto_III` ;

-- -----------------------------------------------------
-- Schema Proyecto_III
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Proyecto_III` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `Proyecto_III` ;

-- -----------------------------------------------------
-- Table `Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuarios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Usuarios` (
  `usuario` VARCHAR(15) NOT NULL,
  `nombreU` VARCHAR(45) NULL,
  `apelU` VARCHAR(45) NULL,
  `doc` VARCHAR(45) NULL,
  `edad` VARCHAR(45) NULL,
  `tel` VARCHAR(45) NULL,
  `pass` VARCHAR(45) NULL,
  PRIMARY KEY (`usuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Administradores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Administradores` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Administradores` (
  `usuario` VARCHAR(15) NOT NULL,
  `pass` VARCHAR(45) NULL,
  `nombreA` VARCHAR(45) NULL,
  `apelA` VARCHAR(45) NULL,
  `doc` VARCHAR(45) NULL,
  `edad` VARCHAR(45) NULL,
  `tel` VARCHAR(45) NULL,
  PRIMARY KEY (`usuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Albumes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Albumes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Albumes` (
  `album` VARCHAR(45) NOT NULL,
  `artista` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `imagen` VARCHAR(150) NULL,
  `precio` INT NULL,
  PRIMARY KEY (`album`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Artistas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Artistas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Artistas` (
  `artista` VARCHAR(45) NOT NULL,
  `vendido` INT NULL,
  PRIMARY KEY (`artista`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Canciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Canciones` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Canciones` (
  `nombre` VARCHAR(45) NULL,
  `album` VARCHAR(45) NULL,
  `duracion` VARCHAR(45) NULL,
  `precio` INT NULL,
  `calidad` VARCHAR(45) NULL,
  `tamaño` VARCHAR(45) NULL)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `AlbumesV`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AlbumesV` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `AlbumesV` (
  `nombreA` VARCHAR(45) NULL,
  `precio` INT NULL,
  `copias` INT NULL,
  `nombreC` VARCHAR(45) NULL)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `CancionesV`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CancionesV` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `CancionesV` (
  `cancion` VARCHAR(45) NOT NULL,
  `copias` INT NULL,
  `precio` INT NULL,
  `nombreC` VARCHAR(45) NULL,
  PRIMARY KEY (`cancion`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
